CC = 		cargo script
CFLAGS =
DAYS = 		day01a day01b day02a day02b

all: $(foreach f, $(DAYS), $(f))

day01a:
	$(CC) day01a.rs < day01.input

day01b:
	$(CC) day01b.rs < day01.input

day02a:
	$(CC) day02a.rs < day02.input

day02b:
	$(CC) day02b.rs < day02.input
